### ISSUE TITLE
Could not save file or find tables

### ISSUE THREAD

**Issue by manhcuong-nguyen** [cellsrg/tabbypdf-web#1]
Hi,

When I used tabbypdf-web, I met this issue : could not save file or find tables. The table can't load.

019-01-22 14:02:19.202 ERROR 10668 --- [           main] org.hibernate.tool.hbm2ddl.SchemaExport  : HHH000389: Unsuccessful: drop table file
2019-01-22 14:02:19.211 ERROR 10668 --- [           main] org.hibernate.tool.hbm2ddl.SchemaExport  : Schema 'SA' does not exist

I used Ubuntu version 16.04
Thank for your help !

**Comment by aaltaev** [comment]
Hi!

I added hibernate auto update ddl property to file applications.properties which is located at src/main/resources, so this should work now. Could you try launching tabbypdf-web again?
Also I recommend to change property file.save.path in the same file to any existing directory on your computer.

Thank you!

**Comment by manhcuong-nguyen** [comment]
Hi,

Thank you ! It worked for me.
